In [14]:
import psycopg2
from psycopg2.extensions import ISOLATION_LEVEL_AUTOCOMMIT

In [2]:
hostname = 'localhost'
username = 'qfixuser'
database = 'qfix'
password = 'QFIXDBpassword'

In [15]:
myConnection = psycopg2.connect( host=hostname, user=username, password=password, dbname=database )
# doQuery( myConnection )
# myConnection.close()

In [21]:
curr = myConnection.cursor()
curr.execute('SELECT * FROM qlogs;')
rows = curr.fetchall()

In [6]:
curr = myConnection.cursor()
curr.execute('SELECT * FROM synth_1_clean_0;')
rows = curr.fetchall()

In [16]:
myConnection.set_isolation_level(ISOLATION_LEVEL_AUTOCOMMIT)

In [23]:
myConnection = psycopg2.connect( host=hostname, user=username, password=password, dbname='qfixtake2' )

In [28]:
curr = myConnection.cursor()
curr.execute('create database "qfixtake2";')
#rows = curr.fetchall()

In [29]:
rows = curr.fetchall()

In [30]:
for row in rows:
    print(row)

(0, 13, 85, 77, 27, 52, 48)
(1, 65, 79, 11, 5, 85, 46)
(2, 76, 1, 46, 73, 26, 95)
(3, 91, 4, 4, 56, 95, 41)
(4, 21, 43, 4, 24, 46, 52)
(5, 23, 24, 23, 48, 32, 7)
(6, 84, 56, 65, 21, 100, 87)
(7, 12, 34, 73, 72, 94, 45)
(8, 83, 68, 32, 60, 89, 86)
(9, 51, 59, 5, 26, 81, 44)
(10, 17, 55, 71, 69, 40, 47)
(11, 51, 78, 53, 41, 51, 7)
(12, 4, 71, 99, 61, 42, 21)
(13, 50, 99, 78, 55, 87, 27)
(14, 51, 96, 59, 47, 30, 57)
(15, 96, 1, 79, 83, 89, 76)
(16, 81, 52, 57, 44, 9, 88)
(17, 57, 20, 51, 50, 38, 38)
(18, 54, 63, 62, 47, 6, 27)
(19, 17, 59, 87, 81, 81, 83)
(20, 25, 85, 68, 11, 5, 6)
(21, 76, 25, 12, 64, 37, 11)
(22, 16, 53, 18, 29, 73, 48)
(23, 32, 48, 4, 40, 44, 23)
(24, 10, 90, 52, 23, 62, 83)
(25, 2, 2, 16, 73, 19, 72)
(26, 68, 55, 23, 98, 81, 54)
(27, 22, 65, 41, 59, 35, 65)
(28, 5, 30, 97, 88, 33, 87)
(29, 31, 94, 75, 43, 28, 5)
(30, 88, 4, 83, 97, 59, 21)
(31, 87, 98, 71, 52, 40, 38)
(32, 20, 68, 44, 22, 14, 68)
(33, 29, 50, 34, 88, 91, 6)
(34, 20, 33, 99, 79, 36, 25)
(35, 68, 84, 94, 36, 89, 70)
(36, 48, 99, 25, 74, 12, 21)
(37, 92, 22, 77, 61, 85, 40)
(38, 34, 30, 87, 62, 96, 90)
(39, 13, 56, 12, 6, 11, 88)
(40, 79, 83, 35, 63, 79, 41)
(41, 57, 23, 10, 29, 90, 59)
(42, 93, 46, 29, 80, 84, 6)
(43, 67, 10, 13, 89, 7, 28)
(44, 99, 43, 13, 19, 27, 76)
(45, 10, 92, 39, 98, 92, 33)
(46, 25, 48, 11, 66, 7, 6)
(47, 99, 30, 61, 47, 34, 11)
(48, 92, 97, 98, 13, 24, 64)
(49, 98, 55, 70, 67, 29, 56)
(50, 31, 25, 10, 30, 99, 47)
(51, 65, 65, 95, 41, 33, 36)
(52, 31, 85, 90, 32, 36, 57)
(53, 58, 60, 26, 4, 27, 11)
(54, 55, 8, 9, 65, 32, 81)
(55, 49, 87, 17, 52, 81, 12)
(56, 95, 18, 78, 99, 83, 35)
(57, 10, 52, 93, 31, 90, 18)
(58, 91, 4, 33, 91, 81, 92)
(59, 84, 75, 70, 20, 45, 20)
(60, 72, 67, 27, 9, 97, 82)
(61, 55, 55, 86, 47, 42, 37)
(62, 26, 3, 65, 43, 59, 10)
(63, 35, 14, 14, 28, 84, 43)
(64, 40, 62, 25, 3, 55, 53)
(65, 65, 44, 69, 74, 27, 52)
(66, 48, 23, 42, 57, 91, 93)
(67, 27, 65, 6, 10, 53, 89)
(68, 16, 77, 89, 33, 71, 86)
(69, 37, 71, 74, 61, 87, 91)
(70, 96, 58, 19, 27, 25, 59)
(71, 76, 6, 69, 73, 37, 54)
(72, 16, 73, 6, 99, 82, 65)
(73, 27, 92, 96, 16, 79, 85)
(74, 66, 71, 46, 93, 98, 41)
(75, 81, 44, 18, 34, 16, 92)
(76, 96, 12, 61, 43, 15, 33)
(77, 25, 75, 2, 21, 46, 7)
(78, 63, 61, 84, 23, 31, 57)
(79, 27, 59, 26, 69, 80, 82)
(80, 98, 55, 50, 86, 78, 59)
(81, 38, 29, 12, 82, 15, 76)
(82, 55, 97, 77, 98, 17, 53)
(83, 57, 32, 51, 37, 55, 5)
(84, 44, 45, 32, 42, 79, 70)
(85, 49, 65, 39, 22, 4, 31)
(86, 60, 89, 84, 53, 99, 49)
(87, 84, 41, 75, 99, 33, 21)
(88, 62, 54, 37, 3, 41, 45)
(89, 40, 87, 59, 74, 91, 76)
(90, 49, 75, 65, 66, 65, 44)
(91, 63, 64, 94, 79, 86, 78)
(92, 82, 61, 36, 28, 72, 88)
(93, 54, 16, 84, 50, 49, 9)
(94, 51, 75, 43, 37, 67, 6)
(95, 51, 95, 70, 42, 70, 63)
(96, 21, 21, 89, 29, 11, 84)
(97, 52, 37, 52, 75, 20, 67)
(98, 72, 82, 28, 62, 26, 58)
(99, 17, 79, 87, 35, 25, 97)
(100, 71, 85, 5, 91, 64, 35)
(101, 43, 77, 79, 21, 64, 20)
(102, 98, 45, 92, 74, 62, 30)
(103, 53, 14, 15, 73, 39, 77)
(104, 24, 72, 73, 32, 14, 43)
(105, 49, 10, 20, 8, 61, 90)
(106, 21, 4, 71, 82, 97, 63)
(107, 34, 84, 13, 70, 13, 43)
(108, 49, 38, 18, 25, 83, 49)
(109, 58, 22, 72, 35, 61, 92)
(110, 100, 5, 80, 87, 34, 41)
(111, 58, 92, 41, 89, 77, 19)
(112, 92, 2, 16, 68, 9, 41)
(113, 13, 47, 85, 91, 7, 10)
(114, 84, 5, 29, 14, 12, 7)
(115, 64, 75, 69, 85, 68, 42)
(116, 63, 97, 65, 26, 9, 94)
(117, 59, 35, 61, 57, 54, 10)
(118, 35, 42, 21, 89, 45, 68)
(119, 72, 75, 73, 76, 28, 98)
(120, 15, 92, 86, 86, 9, 13)
(121, 82, 47, 38, 99, 7, 56)
(122, 44, 13, 41, 72, 89, 7)
(123, 52, 10, 81, 11, 7, 41)
(124, 73, 32, 14, 80, 82, 87)
(125, 30, 43, 26, 57, 36, 37)
(126, 79, 96, 59, 13, 67, 48)
(127, 99, 72, 84, 71, 55, 91)
(128, 83, 30, 17, 39, 54, 14)
(129, 34, 58, 6, 82, 67, 35)
(130, 30, 36, 34, 76, 52, 55)
(131, 15, 92, 34, 35, 10, 99)
(132, 48, 92, 93, 98, 83, 93)
(133, 93, 81, 15, 54, 59, 100)
(134, 79, 71, 75, 38, 95, 66)
(135, 40, 47, 98, 55, 20, 19)
(136, 69, 57, 91, 21, 43, 74)
(137, 5, 10, 56, 29, 14, 30)
(138, 63, 53, 9, 10, 86, 66)
(139, 17, 87, 4, 39, 86, 73)
(140, 28, 90, 61, 87, 90, 45)
(141, 68, 55, 95, 81, 74, 83)
(142, 100, 26, 21, 76, 78, 54)
(143, 49, 41, 89, 81, 60, 8)
(144, 85, 46, 20, 32, 71, 5)
(145, 12, 31, 89, 76, 98, 57)
(146, 57, 56, 54, 56, 83, 96)
(147, 41, 63, 32, 32, 53, 61)
(148, 55, 98, 18, 65, 100, 75)
(149, 57, 37, 41, 94, 90, 69)
(150, 90, 93, 85, 40, 49, 81)
(151, 37, 75, 49, 35, 48, 16)
(152, 35, 42, 3, 19, 29, 87)
(153, 59, 29, 100, 28, 53, 75)
(154, 69, 44, 78, 50, 73, 52)
(155, 98, 72, 11, 15, 97, 27)
(156, 2, 26, 49, 96, 42, 74)
(157, 84, 9, 62, 100, 57, 56)
(158, 35, 95, 97, 13, 57, 45)
(159, 67, 12, 28, 30, 50, 81)
(160, 86, 79, 69, 11, 41, 69)
(161, 29, 51, 91, 14, 86, 15)
(162, 39, 91, 21, 54, 44, 90)
(163, 100, 29, 50, 90, 56, 25)
(164, 76, 34, 50, 3, 99, 68)
(165, 93, 97, 28, 55, 46, 77)
(166, 85, 23, 29, 72, 43, 17)
(167, 19, 57, 61, 97, 55, 63)
(168, 15, 42, 29, 71, 29, 25)
(169, 37, 48, 35, 62, 21, 89)
(170, 70, 54, 7, 34, 70, 66)
(171, 82, 90, 33, 51, 36, 17)
(172, 14, 26, 10, 55, 72, 59)
(173, 69, 23, 21, 58, 89, 45)
(174, 0, 3, 32, 63, 12, 26)
(175, 68, 99, 35, 61, 54, 7)
(176, 33, 14, 26, 78, 70, 8)
(177, 7, 73, 12, 34, 30, 9)
(178, 3, 14, 41, 94, 65, 28)
(179, 68, 28, 53, 34, 96, 38)
(180, 81, 65, 85, 62, 88, 43)
(181, 68, 63, 54, 58, 55, 42)
(182, 90, 64, 56, 8, 53, 21)
(183, 21, 44, 56, 27, 30, 55)
(184, 47, 41, 12, 39, 67, 57)
(185, 55, 85, 73, 70, 6, 34)
(186, 68, 16, 92, 16, 89, 25)
(187, 85, 85, 35, 90, 19, 86)
(188, 38, 44, 13, 61, 30, 69)
(189, 80, 61, 2, 96, 93, 66)
(190, 38, 57, 89, 48, 79, 62)
(191, 42, 94, 42, 62, 9, 50)
(192, 3, 71, 2, 7, 14, 18)
(193, 51, 36, 28, 99, 92, 67)
(194, 81, 82, 26, 82, 27, 58)
(195, 36, 16, 78, 92, 34, 89)
(196, 34, 66, 100, 78, 9, 46)
(197, 38, 30, 82, 46, 71, 65)
(198, 52, 6, 68, 90, 20, 66)
(199, 49, 35, 72, 98, 6, 91)
(200, 38, 84, 19, 73, 13, 37)
(201, 97, 66, 79, 48, 49, 52)
(202, 78, 73, 21, 46, 56, 59)
(203, 93, 84, 16, 39, 14, 7)
(204, 7, 19, 77, 68, 81, 32)
(205, 15, 98, 83, 95, 5, 43)
(206, 64, 74, 92, 55, 41, 5)
(207, 81, 99, 91, 67, 37, 27)
(208, 78, 94, 97, 20, 60, 54)
(209, 43, 80, 94, 74, 71, 71)
(210, 66, 54, 26, 79, 15, 66)
(211, 39, 56, 65, 49, 98, 27)
(212, 1, 96, 32, 30, 44, 62)
(213, 99, 71, 33, 55, 47, 53)
(214, 42, 17, 41, 41, 23, 83)
(215, 36, 16, 58, 85, 79, 64)
(216, 73, 34, 16, 27, 37, 31)
(217, 47, 15, 14, 27, 23, 81)
(218, 54, 20, 44, 88, 60, 58)
(219, 39, 20, 63, 10, 80, 10)
(220, 75, 39, 69, 60, 16, 56)
(221, 7, 25, 39, 30, 68, 99)
(222, 36, 84, 24, 72, 37, 56)
(223, 8, 83, 22, 48, 32, 82)
(224, 59, 62, 76, 27, 9, 84)
(225, 31, 82, 96, 64, 14, 86)
(226, 63, 25, 22, 52, 15, 91)
(227, 71, 82, 39, 93, 16, 73)
(228, 25, 1, 13, 22, 78, 41)
(229, 48, 62, 28, 65, 69, 93)
(230, 50, 86, 97, 78, 44, 31)
(231, 9, 84, 14, 57, 48, 9)
(232, 21, 83, 55, 93, 92, 14)
(233, 68, 5, 43, 46, 96, 62)
(234, 19, 51, 53, 22, 38, 89)
(235, 99, 78, 8, 91, 48, 85)
(236, 17, 15, 91, 30, 8, 53)
(237, 100, 84, 41, 100, 81, 85)
(238, 65, 40, 91, 49, 94, 58)
(239, 91, 48, 44, 60, 34, 19)
(240, 59, 86, 29, 87, 80, 79)
(241, 41, 100, 80, 59, 15, 60)
(242, 1, 91, 35, 39, 57, 66)
(243, 58, 49, 64, 86, 47, 53)
(244, 81, 1, 17, 34, 24, 91)
(245, 14, 11, 33, 52, 83, 100)
(246, 86, 61, 5, 9, 65, 83)
(247, 26, 97, 56, 59, 64, 12)
(248, 17, 94, 28, 11, 31, 74)
(249, 26, 22, 29, 50, 75, 33)
(250, 88, 98, 83, 10, 34, 93)
(251, 86, 14, 45, 38, 76, 7)
(252, 31, 75, 89, 6, 61, 68)
(253, 88, 43, 98, 22, 15, 17)
(254, 59, 13, 28, 22, 9, 97)
(255, 33, 97, 73, 24, 94, 5)
(256, 99, 4, 27, 57, 4, 78)
(257, 8, 82, 5, 54, 24, 32)
(258, 49, 38, 40, 67, 22, 22)
(259, 69, 30, 94, 44, 49, 7)
(260, 2, 11, 63, 68, 96, 46)
(261, 71, 35, 9, 44, 72, 82)
(262, 96, 84, 57, 56, 52, 50)
(263, 68, 58, 86, 47, 49, 84)
(264, 68, 53, 57, 81, 62, 29)
(265, 31, 61, 6, 47, 90, 27)
(266, 44, 70, 93, 71, 64, 41)
(267, 44, 65, 37, 79, 4, 77)
(268, 74, 31, 3, 36, 61, 80)
(269, 87, 21, 10, 14, 99, 66)
(270, 12, 70, 96, 62, 26, 97)
(271, 70, 19, 77, 52, 59, 40)
(272, 29, 43, 54, 48, 88, 12)
(273, 20, 94, 62, 63, 65, 28)
(274, 39, 22, 17, 99, 76, 89)
(275, 0, 71, 32, 51, 69, 7)
(276, 37, 56, 88, 53, 34, 62)
(277, 58, 30, 56, 30, 5, 34)
(278, 8, 50, 51, 88, 76, 76)
(279, 99, 27, 38, 25, 13, 54)
(280, 51, 13, 93, 98, 10, 5)
(281, 6, 74, 86, 9, 4, 56)
(282, 33, 2, 2, 23, 23, 33)
(283, 55, 26, 25, 23, 90, 27)
(284, 56, 46, 34, 42, 5, 22)
(285, 64, 77, 23, 20, 91, 14)
(286, 80, 88, 16, 84, 18, 9)
(287, 28, 35, 60, 46, 80, 68)
(288, 12, 21, 75, 14, 96, 82)
(289, 22, 29, 26, 44, 28, 8)
(290, 25, 20, 36, 47, 88, 68)
(291, 62, 87, 40, 44, 27, 84)
(292, 88, 92, 61, 14, 11, 81)
(293, 89, 54, 93, 94, 77, 40)
(294, 46, 36, 41, 49, 5, 17)
(295, 16, 57, 88, 72, 18, 48)
(296, 63, 14, 9, 62, 26, 66)
(297, 17, 86, 32, 44, 57, 90)
(298, 92, 85, 69, 9, 22, 56)
(299, 99, 73, 20, 37, 97, 53)
(300, 87, 86, 79, 64, 68, 37)
(301, 12, 95, 5, 29, 63, 97)
(302, 21, 25, 85, 35, 43, 39)
(303, 4, 95, 71, 3, 13, 18)
(304, 37, 90, 15, 25, 34, 54)
(305, 91, 54, 91, 56, 45, 88)
(306, 58, 48, 52, 37, 46, 12)
(307, 20, 77, 15, 23, 19, 39)
(308, 4, 37, 62, 69, 88, 13)
(309, 65, 20, 35, 59, 85, 69)
(310, 99, 2, 33, 50, 7, 10)
(311, 37, 56, 15, 9, 34, 76)
(312, 57, 100, 61, 90, 59, 51)
(313, 41, 8, 8, 67, 87, 6)
(314, 18, 33, 32, 84, 28, 34)
(315, 49, 96, 31, 65, 8, 46)
(316, 93, 22, 37, 67, 58, 60)
(317, 61, 68, 33, 37, 42, 55)
(318, 57, 88, 41, 47, 84, 98)
(319, 24, 74, 26, 75, 7, 53)
(320, 57, 70, 92, 80, 58, 52)
(321, 1, 56, 57, 75, 20, 61)
(322, 5, 73, 83, 45, 70, 68)
(323, 30, 9, 77, 37, 19, 47)
(324, 84, 96, 58, 98, 20, 52)
(325, 0, 24, 88, 8, 67, 53)
(326, 99, 100, 14, 28, 100, 36)
(327, 18, 92, 63, 33, 57, 46)
(328, 46, 56, 18, 63, 96, 61)
(329, 79, 29, 17, 3, 99, 16)
(330, 38, 66, 74, 63, 46, 83)
(331, 44, 84, 7, 73, 13, 42)
(332, 44, 19, 46, 86, 7, 23)
(333, 98, 45, 40, 92, 79, 21)
(334, 60, 19, 78, 57, 81, 11)
(335, 93, 23, 86, 46, 90, 14)
(336, 5, 47, 94, 48, 53, 20)
(337, 54, 43, 89, 75, 50, 19)
(338, 14, 98, 62, 25, 82, 25)
(339, 45, 88, 12, 13, 9, 19)
(340, 37, 33, 29, 4, 51, 47)
(341, 74, 31, 59, 33, 77, 21)
(342, 49, 45, 47, 55, 56, 35)
(343, 83, 96, 57, 65, 74, 35)
(344, 59, 47, 49, 41, 56, 25)
(345, 24, 21, 60, 27, 79, 91)
(346, 76, 33, 95, 36, 39, 62)
(347, 66, 41, 79, 86, 31, 26)
(348, 40, 70, 68, 20, 41, 91)
(349, 96, 61, 79, 85, 25, 11)
(350, 61, 39, 72, 31, 46, 82)
(351, 9, 41, 17, 55, 75, 99)
(352, 76, 15, 45, 56, 65, 72)
(353, 98, 95, 22, 18, 98, 20)
(354, 97, 12, 59, 15, 16, 37)
(355, 80, 71, 33, 16, 38, 21)
(356, 23, 50, 50, 93, 12, 56)
(357, 57, 15, 37, 16, 90, 38)
(358, 6, 48, 54, 89, 73, 24)
(359, 91, 1, 71, 7, 83, 23)
(360, 80, 82, 78, 13, 42, 15)
(361, 72, 100, 53, 66, 68, 18)
(362, 37, 35, 76, 43, 39, 57)
(363, 20, 7, 25, 5, 68, 48)
(364, 62, 57, 7, 82, 83, 5)
(365, 43, 79, 43, 87, 71, 68)
(366, 91, 78, 59, 7, 48, 71)
(367, 52, 59, 36, 85, 27, 66)
(368, 44, 15, 3, 15, 31, 50)
(369, 2, 7, 80, 99, 45, 50)
(370, 60, 10, 55, 69, 95, 66)
(371, 55, 42, 92, 54, 50, 75)
(372, 44, 7, 60, 87, 39, 14)
(373, 10, 91, 12, 67, 12, 54)
(374, 92, 24, 32, 62, 59, 58)
(375, 39, 5, 60, 30, 64, 47)
(376, 27, 100, 33, 98, 50, 56)
(377, 27, 18, 71, 47, 60, 22)
(378, 51, 66, 77, 68, 44, 70)
(379, 60, 48, 64, 33, 10, 19)
(380, 98, 90, 83, 28, 85, 80)
(381, 54, 31, 12, 100, 100, 86)
(382, 45, 73, 92, 56, 16, 98)
(383, 54, 77, 63, 9, 48, 6)
(384, 26, 97, 70, 58, 14, 70)
(385, 61, 64, 70, 93, 47, 63)
(386, 53, 59, 69, 21, 9, 16)
(387, 4, 56, 32, 79, 19, 19)
(388, 87, 9, 36, 70, 58, 30)
(389, 13, 58, 26, 86, 29, 94)
(390, 2, 62, 29, 49, 46, 82)
(391, 18, 77, 5, 65, 83, 46)
(392, 85, 36, 37, 92, 100, 80)
(393, 23, 95, 38, 88, 35, 25)
(394, 26, 70, 98, 54, 14, 70)
(395, 90, 79, 2, 33, 79, 72)
(396, 100, 90, 81, 70, 40, 8)
(397, 77, 46, 87, 15, 87, 66)
(398, 89, 71, 45, 53, 13, 28)
(399, 58, 18, 37, 66, 61, 90)
(400, 43, 56, 43, 76, 64, 95)
(401, 14, 13, 30, 63, 65, 24)
(402, 27, 60, 28, 84, 14, 80)
(403, 15, 72, 79, 95, 91, 7)
(404, 66, 92, 78, 47, 76, 32)
(405, 81, 41, 98, 5, 60, 17)
(406, 77, 98, 50, 85, 26, 7)
(407, 81, 42, 10, 68, 91, 13)
(408, 61, 35, 6, 10, 8, 34)
(409, 31, 54, 63, 86, 87, 21)
(410, 63, 88, 26, 62, 99, 65)
(411, 70, 32, 100, 84, 35, 33)
(412, 0, 49, 88, 79, 18, 28)
(413, 16, 26, 22, 19, 57, 92)
(414, 86, 63, 33, 92, 24, 8)
(415, 21, 80, 71, 33, 25, 66)
(416, 51, 80, 46, 11, 10, 27)
(417, 52, 72, 57, 3, 96, 48)
(418, 54, 20, 26, 23, 62, 92)
(419, 26, 35, 30, 5, 5, 79)
(420, 98, 5, 9, 47, 33, 28)
(421, 87, 20, 21, 91, 64, 70)
(422, 67, 3, 98, 5, 26, 50)
(423, 84, 95, 2, 16, 5, 18)
(424, 92, 9, 55, 22, 4, 31)
(425, 26, 55, 88, 54, 55, 31)
(426, 18, 48, 41, 91, 24, 7)
(427, 5, 32, 23, 41, 89, 74)
(428, 59, 84, 89, 9, 70, 17)
(429, 41, 39, 28, 7, 22, 72)
(430, 96, 91, 4, 58, 22, 55)
(431, 53, 17, 10, 50, 9, 85)
(432, 89, 2, 81, 85, 7, 61)
(433, 47, 18, 83, 58, 82, 94)
(434, 97, 67, 88, 9, 36, 50)
(435, 51, 37, 82, 60, 86, 47)
(436, 95, 36, 100, 58, 40, 64)
(437, 10, 69, 61, 81, 11, 45)
(438, 59, 7, 77, 91, 64, 78)
(439, 95, 46, 52, 90, 69, 31)
(440, 59, 77, 85, 15, 20, 70)
(441, 72, 73, 50, 40, 97, 29)
(442, 28, 3, 10, 64, 68, 26)
(443, 74, 18, 38, 65, 79, 48)
(444, 81, 48, 67, 84, 58, 59)
(445, 94, 4, 3, 6, 34, 56)
(446, 62, 69, 3, 88, 27, 97)
(447, 34, 85, 72, 5, 53, 42)
(448, 100, 24, 41, 20, 4, 56)
(449, 62, 17, 84, 24, 94, 69)
(450, 98, 44, 85, 62, 73, 44)
(451, 51, 28, 35, 93, 11, 84)
(452, 75, 17, 44, 84, 53, 53)
(453, 50, 18, 100, 76, 31, 38)
(454, 71, 88, 56, 31, 38, 57)
(455, 89, 71, 24, 4, 67, 30)
(456, 88, 17, 100, 81, 28, 6)
(457, 82, 12, 17, 40, 20, 14)
(458, 55, 66, 79, 8, 8, 50)
(459, 74, 21, 60, 13, 91, 88)
(460, 94, 39, 10, 83, 46, 38)
(461, 43, 71, 74, 45, 29, 19)
(462, 5, 97, 97, 9, 61, 98)
(463, 58, 98, 16, 73, 85, 16)
(464, 20, 95, 25, 63, 92, 73)
(465, 78, 30, 86, 16, 42, 51)
(466, 71, 4, 9, 39, 19, 92)
(467, 44, 59, 44, 87, 93, 91)
(468, 8, 62, 78, 92, 57, 50)
(469, 17, 1, 4, 30, 73, 43)
(470, 54, 28, 98, 93, 29, 41)
(471, 10, 40, 25, 74, 34, 70)
(472, 2, 71, 65, 31, 78, 87)
(473, 91, 70, 45, 60, 77, 35)
(474, 89, 79, 70, 77, 8, 83)
(475, 45, 69, 66, 44, 75, 87)
(476, 100, 2, 92, 78, 61, 78)
(477, 35, 41, 6, 93, 82, 54)
(478, 61, 83, 18, 58, 74, 60)
(479, 98, 26, 69, 79, 41, 95)
(480, 41, 15, 18, 41, 99, 92)
(481, 90, 67, 51, 65, 62, 96)
(482, 39, 40, 74, 81, 75, 20)
(483, 63, 27, 29, 28, 4, 16)
(484, 67, 80, 12, 95, 49, 80)
(485, 4, 8, 82, 12, 7, 68)
(486, 4, 42, 82, 14, 85, 92)
(487, 98, 62, 83, 18, 59, 89)
(488, 87, 18, 84, 42, 53, 81)
(489, 67, 33, 86, 94, 82, 9)
(490, 1, 58, 11, 11, 88, 9)
(491, 28, 31, 94, 95, 80, 49)
(492, 11, 97, 24, 65, 79, 53)
(493, 89, 94, 38, 72, 13, 46)
(494, 67, 28, 38, 77, 24, 93)
(495, 14, 23, 62, 25, 85, 39)
(496, 12, 67, 44, 64, 14, 10)
(497, 29, 52, 21, 23, 85, 28)
(498, 35, 88, 100, 78, 17, 78)
(499, 9, 80, 29, 24, 45, 18)
(500, 67, 83, 67, 81, 19, 31)
(501, 84, 33, 75, 58, 18, 26)
(502, 93, 91, 61, 4, 5, 95)
(503, 80, 70, 27, 92, 11, 71)
(504, 69, 38, 82, 21, 97, 94)
(505, 34, 33, 80, 36, 61, 71)
(506, 95, 76, 29, 37, 11, 82)
(507, 85, 23, 48, 36, 31, 7)
(508, 60, 96, 18, 76, 78, 56)
(509, 85, 43, 63, 9, 18, 61)
(510, 85, 48, 94, 51, 43, 80)
(511, 92, 91, 67, 24, 33, 58)
(512, 3, 30, 80, 27, 66, 34)
(513, 13, 34, 33, 30, 34, 93)
(514, 58, 50, 28, 31, 81, 37)
(515, 15, 39, 68, 95, 84, 52)
(516, 17, 89, 5, 60, 98, 35)
(517, 52, 31, 43, 13, 63, 72)
(518, 13, 2, 25, 37, 46, 73)
(519, 52, 4, 3, 46, 20, 82)
(520, 75, 81, 63, 23, 80, 32)
(521, 16, 4, 40, 96, 70, 68)
(522, 38, 44, 92, 100, 36, 61)
(523, 49, 21, 52, 11, 81, 43)
(524, 66, 79, 25, 95, 99, 51)
(525, 7, 64, 69, 24, 79, 32)
(526, 26, 9, 63, 77, 71, 34)
(527, 30, 6, 19, 27, 24, 9)
(528, 40, 1, 51, 3, 41, 14)
(529, 16, 70, 9, 79, 70, 66)
(530, 53, 73, 23, 42, 5, 5)
(531, 41, 62, 97, 85, 9, 93)
(532, 39, 42, 17, 11, 47, 57)
(533, 86, 67, 20, 61, 83, 28)
(534, 29, 26, 98, 17, 65, 39)
(535, 73, 51, 23, 87, 56, 7)
(536, 22, 17, 33, 18, 66, 63)
(537, 39, 26, 64, 39, 78, 87)
(538, 72, 94, 31, 86, 43, 87)
(539, 62, 29, 29, 86, 50, 19)
(540, 58, 15, 8, 28, 79, 24)
(541, 87, 5, 35, 3, 70, 64)
(542, 79, 82, 91, 44, 39, 63)
(543, 49, 20, 44, 41, 90, 12)
(544, 73, 71, 92, 58, 72, 16)
(545, 88, 6, 62, 14, 26, 71)
(546, 38, 69, 23, 12, 37, 53)
(547, 81, 87, 39, 95, 58, 22)
(548, 50, 68, 77, 14, 98, 58)
(549, 0, 29, 84, 8, 34, 70)
(550, 12, 72, 60, 29, 82, 12)
(551, 19, 77, 61, 24, 42, 86)
(552, 17, 7, 51, 22, 70, 28)
(553, 19, 62, 97, 56, 97, 100)
(554, 75, 58, 38, 10, 55, 22)
(555, 57, 44, 57, 59, 58, 94)
(556, 55, 12, 89, 75, 39, 47)
(557, 56, 40, 68, 100, 9, 93)
(558, 99, 87, 47, 67, 49, 40)
(559, 15, 21, 49, 30, 24, 63)
(560, 28, 84, 10, 25, 45, 25)
(561, 84, 50, 8, 22, 71, 34)
(562, 30, 22, 3, 77, 35, 28)
(563, 10, 51, 75, 95, 94, 6)
(564, 50, 49, 56, 44, 93, 62)
(565, 44, 97, 53, 3, 64, 97)
(566, 65, 20, 84, 6, 86, 17)
(567, 84, 18, 16, 27, 52, 71)
(568, 51, 8, 95, 85, 39, 8)
(569, 41, 97, 96, 19, 23, 98)
(570, 34, 70, 93, 83, 82, 63)
(571, 81, 24, 91, 23, 15, 78)
(572, 100, 76, 63, 11, 55, 22)
(573, 54, 41, 15, 56, 80, 73)
(574, 14, 94, 94, 38, 98, 23)
(575, 40, 85, 10, 41, 4, 25)
(576, 35, 84, 63, 12, 81, 77)
(577, 30, 18, 74, 94, 25, 36)
(578, 33, 97, 7, 4, 21, 49)
(579, 97, 4, 80, 54, 90, 97)
(580, 72, 25, 92, 4, 99, 44)
(581, 27, 89, 51, 40, 33, 45)
(582, 25, 52, 45, 28, 4, 19)
(583, 78, 71, 93, 17, 93, 90)
(584, 35, 96, 99, 85, 58, 88)
(585, 15, 14, 15, 71, 97, 23)
(586, 13, 89, 88, 15, 7, 31)
(587, 27, 1, 16, 84, 10, 48)
(588, 72, 72, 32, 16, 45, 39)
(589, 45, 30, 49, 98, 4, 27)
(590, 85, 50, 79, 10, 100, 5)
(591, 79, 25, 72, 81, 75, 96)
(592, 22, 86, 63, 20, 25, 13)
(593, 91, 34, 36, 14, 81, 58)
(594, 20, 80, 55, 80, 72, 46)
(595, 35, 90, 19, 12, 87, 70)
(596, 93, 62, 100, 45, 10, 68)
(597, 25, 40, 38, 34, 54, 62)
(598, 7, 90, 36, 75, 37, 16)
(599, 33, 23, 32, 68, 69, 23)
(600, 71, 62, 18, 59, 9, 68)
(601, 26, 59, 94, 72, 58, 59)
(602, 25, 47, 7, 51, 97, 53)
(603, 75, 91, 58, 15, 100, 53)
(604, 43, 7, 73, 85, 55, 22)
(605, 71, 19, 36, 26, 55, 67)
(606, 56, 17, 25, 24, 53, 97)
(607, 66, 86, 10, 5, 56, 27)
(608, 33, 74, 11, 89, 44, 62)
(609, 4, 7, 68, 6, 65, 34)
(610, 30, 96, 87, 33, 41, 33)
(611, 12, 96, 66, 73, 45, 25)
(612, 63, 25, 92, 95, 97, 25)
(613, 29, 87, 48, 57, 73, 25)
(614, 46, 9, 5, 97, 74, 64)
(615, 20, 30, 93, 100, 66, 93)
(616, 39, 85, 74, 24, 93, 6)
(617, 27, 50, 94, 37, 14, 74)
(618, 67, 12, 70, 41, 44, 95)
(619, 84, 98, 71, 40, 40, 18)
(620, 6, 52, 17, 60, 24, 53)
(621, 90, 47, 93, 32, 17, 72)
(622, 43, 67, 59, 45, 39, 25)
(623, 100, 21, 47, 90, 83, 99)
(624, 62, 29, 87, 9, 95, 47)
(625, 68, 90, 53, 83, 85, 53)
(626, 92, 25, 17, 72, 83, 44)
(627, 3, 43, 24, 10, 20, 62)
(628, 38, 80, 23, 62, 30, 32)
(629, 15, 75, 29, 68, 70, 58)
(630, 66, 69, 11, 78, 54, 83)
(631, 11, 6, 66, 33, 99, 34)
(632, 45, 35, 57, 23, 97, 31)
(633, 92, 99, 35, 83, 90, 8)
(634, 98, 39, 35, 81, 20, 7)
(635, 97, 2, 65, 58, 44, 84)
(636, 82, 3, 63, 87, 41, 16)
(637, 57, 2, 39, 51, 24, 61)
(638, 83, 48, 55, 21, 4, 50)
(639, 25, 64, 11, 47, 54, 80)
(640, 5, 89, 17, 92, 82, 90)
(641, 93, 9, 37, 61, 36, 68)
(642, 87, 21, 33, 88, 36, 12)
(643, 75, 30, 59, 9, 58, 83)
(644, 44, 37, 78, 54, 50, 21)
(645, 68, 83, 2, 33, 67, 19)
(646, 86, 14, 26, 47, 17, 91)
(647, 51, 39, 62, 76, 56, 67)
(648, 68, 44, 29, 15, 68, 41)
(649, 96, 28, 79, 46, 19, 42)
(650, 63, 68, 36, 25, 19, 61)
(651, 68, 91, 50, 35, 81, 65)
(652, 73, 7, 83, 41, 69, 12)
(653, 0, 4, 9, 11, 87, 57)
(654, 6, 100, 44, 69, 68, 39)
(655, 83, 97, 42, 37, 45, 84)
(656, 50, 11, 3, 67, 18, 78)
(657, 60, 22, 8, 68, 19, 99)
(658, 51, 33, 81, 63, 67, 80)
(659, 45, 5, 17, 100, 64, 7)
(660, 14, 11, 27, 67, 93, 59)
(661, 50, 93, 14, 91, 66, 27)
(662, 77, 18, 60, 48, 14, 94)
(663, 19, 37, 65, 29, 13, 33)
(664, 38, 81, 55, 93, 17, 84)
(665, 99, 99, 31, 12, 78, 47)
(666, 64, 10, 97, 41, 97, 5)
(667, 29, 47, 38, 23, 99, 57)
(668, 94, 52, 79, 65, 17, 72)
(669, 75, 72, 50, 7, 84, 97)
(670, 6, 5, 44, 75, 47, 83)
(671, 88, 60, 63, 66, 39, 24)
(672, 91, 26, 83, 53, 75, 80)
(673, 89, 84, 34, 84, 88, 66)
(674, 20, 99, 81, 40, 33, 83)
(675, 66, 38, 91, 100, 69, 84)
(676, 60, 31, 81, 71, 89, 38)
(677, 94, 70, 76, 85, 48, 85)
(678, 89, 98, 61, 9, 27, 23)

In [31]:
def postgre2CSVQuerys(tableName,fileName,hostname='localhost',username='qfixuser',database='qfix',password='QFIXDBpassword'):
    myConnection = psycopg2.connect( host=hostname, user=username, password=password, dbname=database )
    curr = myConnection.cursor()
    curr.execute('SELECT * FROM {};'.format(tableName))
    rows = curr.fetchall()
    queryList = []
    for row in rows:
        queryList.append(row[-1])
    queryString = '\n'.join(queryList)
    with open(fileName,'w') as f:
        f.write(queryString)

In [ ]:
def postgre2CSVData(tableName,fileName,hostname='localhost',username='qfixuser',database='qfix',password='QFIXDBpassword'):
    myConnection = psycopg2.connect( host=hostname, user=username, password=password, dbname=database )
    curr = myConnection.cursor()
    curr.execute('SELECT * FROM {};'.format(tableName))
    rows = curr.fetchall()
    queryList = []
    for row in rows:
        queryList.append(row)
    queryString = '\n'.join(queryList)
    with open(fileName,'w') as f:
        f.write(queryString)

In [7]:
for row in rows:
    print(row)

(0, 13, 85, 77, 27, 52, 48)
(1, 65, 79, 11, 5, 85, 46)
(2, 76, 1, 46, 73, 26, 95)
(3, 91, 4, 4, 56, 95, 41)
(4, 21, 43, 4, 24, 46, 52)
(5, 23, 24, 23, 48, 32, 7)
(6, 84, 56, 65, 21, 100, 87)
(7, 12, 34, 73, 72, 94, 45)
(8, 83, 68, 32, 60, 89, 86)
(9, 51, 59, 5, 26, 81, 44)
(10, 17, 55, 71, 69, 40, 47)
(11, 51, 78, 53, 41, 51, 7)
(12, 4, 71, 99, 61, 42, 21)
(13, 50, 99, 78, 55, 87, 27)
(14, 51, 96, 59, 47, 30, 57)
(15, 96, 1, 79, 83, 89, 76)
(16, 81, 52, 57, 44, 9, 88)
(17, 57, 20, 51, 50, 38, 38)
(18, 54, 63, 62, 47, 6, 27)
(19, 17, 59, 87, 81, 81, 83)
(20, 25, 85, 68, 11, 5, 6)
(21, 76, 25, 12, 64, 37, 11)
(22, 16, 53, 18, 29, 73, 48)
(23, 32, 48, 4, 40, 44, 23)
(24, 10, 90, 52, 23, 62, 83)
(25, 2, 2, 16, 73, 19, 72)
(26, 68, 55, 23, 98, 81, 54)
(27, 22, 65, 41, 59, 35, 65)
(28, 5, 30, 97, 88, 33, 87)
(29, 31, 94, 75, 43, 28, 5)
(30, 88, 4, 83, 97, 59, 21)
(31, 87, 98, 71, 52, 40, 38)
(32, 20, 68, 44, 22, 14, 68)
(33, 29, 50, 34, 88, 91, 6)
(34, 20, 33, 99, 79, 36, 25)
(35, 68, 84, 94, 36, 89, 70)
(36, 48, 99, 25, 74, 12, 21)
(37, 92, 22, 77, 61, 85, 40)
(38, 34, 30, 87, 62, 96, 90)
(39, 13, 56, 12, 6, 11, 88)
(40, 79, 83, 35, 63, 79, 41)
(41, 57, 23, 10, 29, 90, 59)
(42, 93, 46, 29, 80, 84, 6)
(43, 67, 10, 13, 89, 7, 28)
(44, 99, 43, 13, 19, 27, 76)
(45, 10, 92, 39, 98, 92, 33)
(46, 25, 48, 11, 66, 7, 6)
(47, 99, 30, 61, 47, 34, 11)
(48, 92, 97, 98, 13, 24, 64)
(49, 98, 55, 70, 67, 29, 56)

In [3]:
curr = myConnection.cursor()
curr.execute('SHOW TABLES;')
rows = curr.fetchall()

NameError: name 'myConnection' is not defined

In [5]:
curr = myConnection.cursor()
curr.execute("""SELECT table_name FROM information_schema.tables
       WHERE table_schema = 'public'""")
for table in curr.fetchall():
    print(table)

('synth_4_clean_7',)
('synth_4_clean_8',)
('plots',)
('synth_4_clean_9',)
('synth_4_clean_10',)
('synth_4_dirty_0',)
('synth_4_dirty_1',)
('qlogs',)
('synth_4_dirty_2',)
('configs',)
('exps',)
('synth_4_clean_6',)
('synth_4_dirty_3',)
('synth_4_dirty_4',)
('synth_4_dirty_5',)
('synth_4_dirty_6',)
('synth_1',)
('synth_4_dirty_7',)
('synth_4_dirty_8',)
('synth_4_dirty_9',)
('synth_1_clean_0',)
('synth_1_clean_1',)
('synth_1_clean_2',)
('synth_1_clean_3',)
('synth_1_clean_4',)
('synth_1_clean_5',)
('synth_1_clean_6',)
('synth_1_clean_7',)
('synth_1_clean_8',)
('synth_1_clean_9',)
('synth_1_clean_10',)
('synth_1_dirty_0',)
('synth_1_dirty_1',)
('synth_1_dirty_2',)
('synth_1_dirty_3',)
('synth_1_dirty_4',)
('synth_1_dirty_5',)
('synth_1_dirty_6',)
('synth_1_dirty_7',)
('synth_1_dirty_8',)
('synth_1_dirty_9',)
('synth_1_dirty_10',)
('synth_2_clean_0',)
('synth_2_clean_1',)
('synth_2_clean_2',)
('synth_2',)
('synth_4_dirty_10',)
('synth_2_clean_3',)
('synth_2_clean_4',)
('synth_2_clean_5',)
('synth_2_clean_6',)
('synth_2_clean_7',)
('synth_2_clean_8',)
('synth_2_clean_9',)
('synth_2_clean_10',)
('synth_2_dirty_0',)
('synth_2_dirty_1',)
('synth_2_dirty_2',)
('synth_2_dirty_3',)
('synth_2_dirty_4',)
('synth_2_dirty_5',)
('synth_2_dirty_6',)
('synth_2_dirty_7',)
('synth_2_dirty_8',)
('synth_2_dirty_9',)
('synth_2_dirty_10',)
('synth_3_clean_0',)
('synth_3_clean_1',)
('synth_3_clean_2',)
('synth_3_clean_3',)
('synth_3_clean_4',)
('synth_3_clean_5',)
('synth_3_clean_6',)
('synth_3_clean_7',)
('synth_3_clean_8',)
('synth_3_clean_9',)
('synth_3_clean_10',)
('synth_3_dirty_0',)
('synth_3_dirty_1',)
('synth_3',)
('synth_3_dirty_2',)
('synth_3_dirty_3',)
('synth_3_dirty_4',)
('synth_3_dirty_5',)
('synth_3_dirty_6',)
('synth_3_dirty_7',)
('synth_3_dirty_8',)
('synth_3_dirty_9',)
('synth_3_dirty_10',)
('synth_4_clean_0',)
('synth_4_clean_1',)
('synth_4_clean_2',)
('synth_4_clean_3',)
('synth_4_clean_4',)
('synth_4_clean_5',)
('synth_4',)

In [9]:
queryList = []
for row in rows:
    queryList.append(row[-1])

In [11]:
queryString = '\n'.join(queryList)
with open('/home/mj1e16/abduction/pwe/testData/qfixNew/qfix_sync/synth/qlog_New.csv','w') as f:
    f.write(queryString)

In [15]:
for x in rows:
    print(x)

(1, 1, 0, 'synth_1_clean_0', 'synth_1_clean_1', 'clean', 'UPDATE', '[]', '[["a1", 95], ["a2", 91]]', '[["a1", "=", 3], ["a5", "=", 2]]', 'UPDATE synth_1_clean_0 SET a1 = 95, a2 = 91 WHERE a1 = 3 AND a5 = 2')
(2, 1, 1, 'synth_1_clean_1', 'synth_1_clean_2', 'clean', 'UPDATE', '[]', '[["a1", 38], ["a2", 21]]', '[["a1", ">=", 38], ["a1", "<", 48], ["a4", ">=", 2], ["a4", "<", 12]]', 'UPDATE synth_1_clean_1 SET a1 = 38, a2 = 21 WHERE a1 >= 38 AND a1 < 48 AND a4 >= 2 AND a4 < 12')
(3, 1, 2, 'synth_1_clean_2', 'synth_1_clean_3', 'clean', 'INSERT', '[50, 44, 50, 23, 23, 22, 46]', '[]', '[]', 'INSERT INTO synth_1_clean_2 VALUES(50,44,50,23,23,22,46)')
(4, 1, 3, 'synth_1_clean_3', 'synth_1_clean_4', 'clean', 'INSERT', '[51, 2, 84, 56, 64, 18, 100]', '[]', '[]', 'INSERT INTO synth_1_clean_3 VALUES(51,2,84,56,64,18,100)')
(5, 1, 4, 'synth_1_clean_4', 'synth_1_clean_5', 'clean', 'UPDATE', '[]', '[["a1", 33], ["a2", 72]]', '[["a1", "=", 71], ["a5", "=", 94]]', 'UPDATE synth_1_clean_4 SET a1 = 33, a2 = 72 WHERE a1 = 71 AND a5 = 94')
(6, 1, 5, 'synth_1_clean_5', 'synth_1_clean_6', 'clean', 'UPDATE', '[]', '[["a1", 67], ["a2", 30]]', '[["a1", ">=", 53], ["a1", "<", 63], ["a4", ">=", 80], ["a4", "<", 90]]', 'UPDATE synth_1_clean_5 SET a1 = 67, a2 = 30 WHERE a1 >= 53 AND a1 < 63 AND a4 >= 80 AND a4 < 90')
(7, 1, 6, 'synth_1_clean_6', 'synth_1_clean_7', 'clean', 'UPDATE', '[]', '[["a1", 59], ["a2", 3]]', '[["a1", ">=", 22], ["a1", "<", 32], ["a4", ">=", 72], ["a4", "<", 82]]', 'UPDATE synth_1_clean_6 SET a1 = 59, a2 = 3 WHERE a1 >= 22 AND a1 < 32 AND a4 >= 72 AND a4 < 82')
(8, 1, 7, 'synth_1_clean_7', 'synth_1_clean_8', 'clean', 'UPDATE', '[]', '[["a1", 55], ["a2", 71]]', '[["a1", "=", 68], ["a5", "=", 37]]', 'UPDATE synth_1_clean_7 SET a1 = 55, a2 = 71 WHERE a1 = 68 AND a5 = 37')
(9, 1, 8, 'synth_1_clean_8', 'synth_1_clean_9', 'clean', 'UPDATE', '[]', '[["a1", 78], ["a2", 52]]', '[["a1", ">=", 35], ["a1", "<", 45], ["a4", ">=", 44], ["a4", "<", 54]]', 'UPDATE synth_1_clean_8 SET a1 = 78, a2 = 52 WHERE a1 >= 35 AND a1 < 45 AND a4 >= 44 AND a4 < 54')
(10, 1, 9, 'synth_1_clean_9', 'synth_1_clean_10', 'clean', 'INSERT', '[52, 4, 71, 99, 59, 39, 17]', '[]', '[]', 'INSERT INTO synth_1_clean_9 VALUES(52,4,71,99,59,39,17)')
(11, 1, 0, 'synth_1_dirty_0', 'synth_1_dirty_1', 'dirty', 'UPDATE', '[]', '[["a1", 95], ["a2", 27]]', '[["a1", "=", 96], ["a5", "=", 2]]', 'UPDATE synth_1_dirty_0 SET a1 = 95, a2 = 27 WHERE a1 = 96 AND a5 = 2')
(12, 1, 1, 'synth_1_dirty_1', 'synth_1_dirty_2', 'dirty', 'UPDATE', '[]', '[["a1", 38], ["a2", 21]]', '[["a1", ">=", 38], ["a1", "<", 48], ["a4", ">=", 2], ["a4", "<", 12]]', 'UPDATE synth_1_dirty_1 SET a1 = 38, a2 = 21 WHERE a1 >= 38 AND a1 < 48 AND a4 >= 2 AND a4 < 12')
(13, 1, 2, 'synth_1_dirty_2', 'synth_1_dirty_3', 'dirty', 'INSERT', '[50, 44, 50, 23, 23, 22, 46]', '[]', '[]', 'INSERT INTO synth_1_dirty_2 VALUES(50,44,50,23,23,22,46)')
(14, 1, 3, 'synth_1_dirty_3', 'synth_1_dirty_4', 'dirty', 'INSERT', '[51, 2, 84, 56, 64, 18, 100]', '[]', '[]', 'INSERT INTO synth_1_dirty_3 VALUES(51,2,84,56,64,18,100)')
(15, 1, 4, 'synth_1_dirty_4', 'synth_1_dirty_5', 'dirty', 'UPDATE', '[]', '[["a1", 33], ["a2", 72]]', '[["a1", "=", 71], ["a5", "=", 94]]', 'UPDATE synth_1_dirty_4 SET a1 = 33, a2 = 72 WHERE a1 = 71 AND a5 = 94')
(16, 1, 5, 'synth_1_dirty_5', 'synth_1_dirty_6', 'dirty', 'UPDATE', '[]', '[["a1", 67], ["a2", 30]]', '[["a1", ">=", 53], ["a1", "<", 63], ["a4", ">=", 80], ["a4", "<", 90]]', 'UPDATE synth_1_dirty_5 SET a1 = 67, a2 = 30 WHERE a1 >= 53 AND a1 < 63 AND a4 >= 80 AND a4 < 90')
(17, 1, 6, 'synth_1_dirty_6', 'synth_1_dirty_7', 'dirty', 'UPDATE', '[]', '[["a1", 59], ["a2", 3]]', '[["a1", ">=", 22], ["a1", "<", 32], ["a4", ">=", 72], ["a4", "<", 82]]', 'UPDATE synth_1_dirty_6 SET a1 = 59, a2 = 3 WHERE a1 >= 22 AND a1 < 32 AND a4 >= 72 AND a4 < 82')
(18, 1, 7, 'synth_1_dirty_7', 'synth_1_dirty_8', 'dirty', 'UPDATE', '[]', '[["a1", 55], ["a2", 71]]', '[["a1", "=", 68], ["a5", "=", 37]]', 'UPDATE synth_1_dirty_7 SET a1 = 55, a2 = 71 WHERE a1 = 68 AND a5 = 37')
(19, 1, 8, 'synth_1_dirty_8', 'synth_1_dirty_9', 'dirty', 'UPDATE', '[]', '[["a1", 78], ["a2", 52]]', '[["a1", ">=", 35], ["a1", "<", 45], ["a4", ">=", 44], ["a4", "<", 54]]', 'UPDATE synth_1_dirty_8 SET a1 = 78, a2 = 52 WHERE a1 >= 35 AND a1 < 45 AND a4 >= 44 AND a4 < 54')
(20, 1, 9, 'synth_1_dirty_9', 'synth_1_dirty_10', 'dirty', 'INSERT', '[52, 4, 71, 99, 59, 39, 17]', '[]', '[]', 'INSERT INTO synth_1_dirty_9 VALUES(52,4,71,99,59,39,17)')
(21, 2, 0, 'synth_2_clean_0', 'synth_2_clean_1', 'clean', 'UPDATE', '[]', '[["a2", 54], ["a1", 44]]', '[["a4", ">=", 24], ["a4", "<", 34], ["a2", ">=", 3], ["a2", "<", 13]]', 'UPDATE synth_2_clean_0 SET a2 = 54, a1 = 44 WHERE a4 >= 24 AND a4 < 34 AND a2 >= 3 AND a2 < 13')
(22, 2, 1, 'synth_2_clean_1', 'synth_2_clean_2', 'clean', 'INSERT', '[50, 46, 32, 38, 90, 53, 56]', '[]', '[]', 'INSERT INTO synth_2_clean_1 VALUES(50,46,32,38,90,53,56)')
(23, 2, 2, 'synth_2_clean_2', 'synth_2_clean_3', 'clean', 'INSERT', '[51, 2, 32, 13, 51, 100, 68]', '[]', '[]', 'INSERT INTO synth_2_clean_2 VALUES(51,2,32,13,51,100,68)')
(24, 2, 3, 'synth_2_clean_3', 'synth_2_clean_4', 'clean', 'INSERT', '[52, 90, 80, 74, 91, 77, 79]', '[]', '[]', 'INSERT INTO synth_2_clean_3 VALUES(52,90,80,74,91,77,79)')
(25, 2, 4, 'synth_2_clean_4', 'synth_2_clean_5', 'clean', 'UPDATE', '[]', '[["a2", 97], ["a1", 16]]', '[["a4", ">=", 68], ["a4", "<", 78], ["a2", ">=", 65], ["a2", "<", 75]]', 'UPDATE synth_2_clean_4 SET a2 = 97, a1 = 16 WHERE a4 >= 68 AND a4 < 78 AND a2 >= 65 AND a2 < 75')
(26, 2, 5, 'synth_2_clean_5', 'synth_2_clean_6', 'clean', 'UPDATE', '[]', '[["a2", 49], ["a1", 93]]', '[["a4", ">=", 45], ["a4", "<", 55], ["a2", ">=", 75], ["a2", "<", 85]]', 'UPDATE synth_2_clean_5 SET a2 = 49, a1 = 93 WHERE a4 >= 45 AND a4 < 55 AND a2 >= 75 AND a2 < 85')
(27, 2, 6, 'synth_2_clean_6', 'synth_2_clean_7', 'clean', 'UPDATE', '[]', '[["a2", 90], ["a1", 46]]', '[["a4", ">=", 51], ["a4", "<", 61], ["a2", ">=", 83], ["a2", "<", 93]]', 'UPDATE synth_2_clean_6 SET a2 = 90, a1 = 46 WHERE a4 >= 51 AND a4 < 61 AND a2 >= 83 AND a2 < 93')
(28, 2, 7, 'synth_2_clean_7', 'synth_2_clean_8', 'clean', 'UPDATE', '[]', '[["a2", 22], ["a1", 32]]', '[["a0", "=", 70], ["a2", "=", 16]]', 'UPDATE synth_2_clean_7 SET a2 = 22, a1 = 32 WHERE a0 = 70 AND a2 = 16')
(29, 2, 8, 'synth_2_clean_8', 'synth_2_clean_9', 'clean', 'UPDATE', '[]', '[["a2", 92], ["a1", 31]]', '[["a0", "=", 96], ["a2", "=", 71]]', 'UPDATE synth_2_clean_8 SET a2 = 92, a1 = 31 WHERE a0 = 96 AND a2 = 71')
(30, 2, 9, 'synth_2_clean_9', 'synth_2_clean_10', 'clean', 'UPDATE', '[]', '[["a2", 65], ["a1", 59]]', '[["a4", ">=", 28], ["a4", "<", 38], ["a2", ">=", 18], ["a2", "<", 28]]', 'UPDATE synth_2_clean_9 SET a2 = 65, a1 = 59 WHERE a4 >= 28 AND a4 < 38 AND a2 >= 18 AND a2 < 28')
(31, 2, 0, 'synth_2_dirty_0', 'synth_2_dirty_1', 'dirty', 'UPDATE', '[]', '[["a2", 54], ["a1", 44]]', '[["a4", ">=", 24], ["a4", "<", 34], ["a2", ">=", 3], ["a2", "<", 13]]', 'UPDATE synth_2_dirty_0 SET a2 = 54, a1 = 44 WHERE a4 >= 24 AND a4 < 34 AND a2 >= 3 AND a2 < 13')
(32, 2, 1, 'synth_2_dirty_1', 'synth_2_dirty_2', 'dirty', 'INSERT', '[50, 46, 32, 38, 90, 53, 56]', '[]', '[]', 'INSERT INTO synth_2_dirty_1 VALUES(50,46,32,38,90,53,56)')
(33, 2, 2, 'synth_2_dirty_2', 'synth_2_dirty_3', 'dirty', 'INSERT', '[51, 2, 32, 10, 51, 100, 68]', '[]', '[]', 'INSERT INTO synth_2_dirty_2 VALUES(51,2,32,10,51,100,68)')
(34, 2, 3, 'synth_2_dirty_3', 'synth_2_dirty_4', 'dirty', 'INSERT', '[52, 90, 80, 74, 91, 77, 79]', '[]', '[]', 'INSERT INTO synth_2_dirty_3 VALUES(52,90,80,74,91,77,79)')
(67, 4, 6, 'synth_4_clean_6', 'synth_4_clean_7', 'clean', 'UPDATE', '[]', '[["a3", 100], ["a2", 19]]', '[["a1", "=", 41], ["a0", "=", 20]]', 'UPDATE synth_4_clean_6 SET a3 = 100, a2 = 19 WHERE a1 = 41 AND a0 = 20')
(35, 2, 4, 'synth_2_dirty_4', 'synth_2_dirty_5', 'dirty', 'UPDATE', '[]', '[["a2", 97], ["a1", 16]]', '[["a4", ">=", 68], ["a4", "<", 78], ["a2", ">=", 65], ["a2", "<", 75]]', 'UPDATE synth_2_dirty_4 SET a2 = 97, a1 = 16 WHERE a4 >= 68 AND a4 < 78 AND a2 >= 65 AND a2 < 75')
(36, 2, 5, 'synth_2_dirty_5', 'synth_2_dirty_6', 'dirty', 'UPDATE', '[]', '[["a2", 49], ["a1", 93]]', '[["a4", ">=", 45], ["a4", "<", 55], ["a2", ">=", 75], ["a2", "<", 85]]', 'UPDATE synth_2_dirty_5 SET a2 = 49, a1 = 93 WHERE a4 >= 45 AND a4 < 55 AND a2 >= 75 AND a2 < 85')
(37, 2, 6, 'synth_2_dirty_6', 'synth_2_dirty_7', 'dirty', 'UPDATE', '[]', '[["a2", 90], ["a1", 46]]', '[["a4", ">=", 51], ["a4", "<", 61], ["a2", ">=", 83], ["a2", "<", 93]]', 'UPDATE synth_2_dirty_6 SET a2 = 90, a1 = 46 WHERE a4 >= 51 AND a4 < 61 AND a2 >= 83 AND a2 < 93')
(38, 2, 7, 'synth_2_dirty_7', 'synth_2_dirty_8', 'dirty', 'UPDATE', '[]', '[["a2", 22], ["a1", 32]]', '[["a0", "=", 70], ["a2", "=", 16]]', 'UPDATE synth_2_dirty_7 SET a2 = 22, a1 = 32 WHERE a0 = 70 AND a2 = 16')
(39, 2, 8, 'synth_2_dirty_8', 'synth_2_dirty_9', 'dirty', 'UPDATE', '[]', '[["a2", 92], ["a1", 31]]', '[["a0", "=", 96], ["a2", "=", 71]]', 'UPDATE synth_2_dirty_8 SET a2 = 92, a1 = 31 WHERE a0 = 96 AND a2 = 71')
(40, 2, 9, 'synth_2_dirty_9', 'synth_2_dirty_10', 'dirty', 'UPDATE', '[]', '[["a2", 65], ["a1", 59]]', '[["a4", ">=", 28], ["a4", "<", 38], ["a2", ">=", 18], ["a2", "<", 28]]', 'UPDATE synth_2_dirty_9 SET a2 = 65, a1 = 59 WHERE a4 >= 28 AND a4 < 38 AND a2 >= 18 AND a2 < 28')
(41, 3, 0, 'synth_3_clean_0', 'synth_3_clean_1', 'clean', 'INSERT', '[50, 64, 87, 52, 74, 67, 6]', '[]', '[]', 'INSERT INTO synth_3_clean_0 VALUES(50,64,87,52,74,67,6)')
(42, 3, 1, 'synth_3_clean_1', 'synth_3_clean_2', 'clean', 'UPDATE', '[]', '[["a0", 30], ["a4", 3]]', '[["a0", ">=", 78], ["a0", "<", 88], ["a4", ">=", 43], ["a4", "<", 53]]', 'UPDATE synth_3_clean_1 SET a0 = 30, a4 = 3 WHERE a0 >= 78 AND a0 < 88 AND a4 >= 43 AND a4 < 53')
(43, 3, 2, 'synth_3_clean_2', 'synth_3_clean_3', 'clean', 'UPDATE', '[]', '[["a0", 72], ["a4", 93]]', '[["a0", ">=", 35], ["a0", "<", 45], ["a4", ">=", 72], ["a4", "<", 82]]', 'UPDATE synth_3_clean_2 SET a0 = 72, a4 = 93 WHERE a0 >= 35 AND a0 < 45 AND a4 >= 72 AND a4 < 82')
(44, 3, 3, 'synth_3_clean_3', 'synth_3_clean_4', 'clean', 'UPDATE', '[]', '[["a0", 88], ["a4", 9]]', '[["a0", ">=", 12], ["a0", "<", 22], ["a4", ">=", 19], ["a4", "<", 29]]', 'UPDATE synth_3_clean_3 SET a0 = 88, a4 = 9 WHERE a0 >= 12 AND a0 < 22 AND a4 >= 19 AND a4 < 29')
(45, 3, 4, 'synth_3_clean_4', 'synth_3_clean_5', 'clean', 'UPDATE', '[]', '[["a0", 63], ["a4", 30]]', '[["a1", "=", 51], ["a2", "=", 38]]', 'UPDATE synth_3_clean_4 SET a0 = 63, a4 = 30 WHERE a1 = 51 AND a2 = 38')
(46, 3, 5, 'synth_3_clean_5', 'synth_3_clean_6', 'clean', 'UPDATE', '[]', '[["a0", 59], ["a4", 91]]', '[["a0", ">=", 62], ["a0", "<", 72], ["a4", ">=", 84], ["a4", "<", 94]]', 'UPDATE synth_3_clean_5 SET a0 = 59, a4 = 91 WHERE a0 >= 62 AND a0 < 72 AND a4 >= 84 AND a4 < 94')
(47, 3, 6, 'synth_3_clean_6', 'synth_3_clean_7', 'clean', 'UPDATE', '[]', '[["a0", 67], ["a4", 16]]', '[["a0", ">=", 78], ["a0", "<", 88], ["a4", ">=", 87], ["a4", "<", 97]]', 'UPDATE synth_3_clean_6 SET a0 = 67, a4 = 16 WHERE a0 >= 78 AND a0 < 88 AND a4 >= 87 AND a4 < 97')
(48, 3, 7, 'synth_3_clean_7', 'synth_3_clean_8', 'clean', 'UPDATE', '[]', '[["a0", 72], ["a4", 21]]', '[["a0", ">=", 75], ["a0", "<", 85], ["a4", ">=", 52], ["a4", "<", 62]]', 'UPDATE synth_3_clean_7 SET a0 = 72, a4 = 21 WHERE a0 >= 75 AND a0 < 85 AND a4 >= 52 AND a4 < 62')
(49, 3, 8, 'synth_3_clean_8', 'synth_3_clean_9', 'clean', 'INSERT', '[51, 6, 86, 99, 8, 80, 41]', '[]', '[]', 'INSERT INTO synth_3_clean_8 VALUES(51,6,86,99,8,80,41)')
(50, 3, 9, 'synth_3_clean_9', 'synth_3_clean_10', 'clean', 'INSERT', '[52, 29, 77, 88, 4, 62, 4]', '[]', '[]', 'INSERT INTO synth_3_clean_9 VALUES(52,29,77,88,4,62,4)')
(51, 3, 0, 'synth_3_dirty_0', 'synth_3_dirty_1', 'dirty', 'INSERT', '[50, 64, 87, 52, 74, 67, 6]', '[]', '[]', 'INSERT INTO synth_3_dirty_0 VALUES(50,64,87,52,74,67,6)')
(52, 3, 1, 'synth_3_dirty_1', 'synth_3_dirty_2', 'dirty', 'UPDATE', '[]', '[["a0", 30], ["a4", 3]]', '[["a0", ">=", 78], ["a0", "<", 88], ["a4", ">=", 43], ["a4", "<", 53]]', 'UPDATE synth_3_dirty_1 SET a0 = 30, a4 = 3 WHERE a0 >= 78 AND a0 < 88 AND a4 >= 43 AND a4 < 53')
(53, 3, 2, 'synth_3_dirty_2', 'synth_3_dirty_3', 'dirty', 'UPDATE', '[]', '[["a0", 72], ["a4", 93]]', '[["a0", ">=", 35], ["a0", "<", 45], ["a4", ">=", 72], ["a4", "<", 82]]', 'UPDATE synth_3_dirty_2 SET a0 = 72, a4 = 93 WHERE a0 >= 35 AND a0 < 45 AND a4 >= 72 AND a4 < 82')
(54, 3, 3, 'synth_3_dirty_3', 'synth_3_dirty_4', 'dirty', 'UPDATE', '[]', '[["a0", 88], ["a4", 9]]', '[["a0", ">=", 12], ["a0", "<", 22], ["a4", ">=", 19], ["a4", "<", 29]]', 'UPDATE synth_3_dirty_3 SET a0 = 88, a4 = 9 WHERE a0 >= 12 AND a0 < 22 AND a4 >= 19 AND a4 < 29')
(55, 3, 4, 'synth_3_dirty_4', 'synth_3_dirty_5', 'dirty', 'UPDATE', '[]', '[["a0", 63], ["a4", 30]]', '[["a1", "=", 51], ["a2", "=", 38]]', 'UPDATE synth_3_dirty_4 SET a0 = 63, a4 = 30 WHERE a1 = 51 AND a2 = 38')
(56, 3, 5, 'synth_3_dirty_5', 'synth_3_dirty_6', 'dirty', 'UPDATE', '[]', '[["a0", 59], ["a4", 91]]', '[["a0", ">=", 62], ["a0", "<", 72], ["a4", ">=", 84], ["a4", "<", 94]]', 'UPDATE synth_3_dirty_5 SET a0 = 59, a4 = 91 WHERE a0 >= 62 AND a0 < 72 AND a4 >= 84 AND a4 < 94')
(57, 3, 6, 'synth_3_dirty_6', 'synth_3_dirty_7', 'dirty', 'UPDATE', '[]', '[["a0", 67], ["a4", 16]]', '[["a0", ">=", 78], ["a0", "<", 88], ["a4", ">=", 87], ["a4", "<", 97]]', 'UPDATE synth_3_dirty_6 SET a0 = 67, a4 = 16 WHERE a0 >= 78 AND a0 < 88 AND a4 >= 87 AND a4 < 97')
(58, 3, 7, 'synth_3_dirty_7', 'synth_3_dirty_8', 'dirty', 'UPDATE', '[]', '[["a0", 72], ["a4", 21]]', '[["a0", ">=", 75], ["a0", "<", 85], ["a4", ">=", 52], ["a4", "<", 62]]', 'UPDATE synth_3_dirty_7 SET a0 = 72, a4 = 21 WHERE a0 >= 75 AND a0 < 85 AND a4 >= 52 AND a4 < 62')
(59, 3, 8, 'synth_3_dirty_8', 'synth_3_dirty_9', 'dirty', 'INSERT', '[51, 6, 86, 4, 8, 80, 41]', '[]', '[]', 'INSERT INTO synth_3_dirty_8 VALUES(51,6,86,4,8,80,41)')
(60, 3, 9, 'synth_3_dirty_9', 'synth_3_dirty_10', 'dirty', 'INSERT', '[52, 29, 77, 88, 4, 62, 4]', '[]', '[]', 'INSERT INTO synth_3_dirty_9 VALUES(52,29,77,88,4,62,4)')
(61, 4, 0, 'synth_4_clean_0', 'synth_4_clean_1', 'clean', 'UPDATE', '[]', '[["a3", 81], ["a2", 80]]', '[["a4", ">=", 17], ["a4", "<", 27], ["a2", ">=", 28], ["a2", "<", 38]]', 'UPDATE synth_4_clean_0 SET a3 = 81, a2 = 80 WHERE a4 >= 17 AND a4 < 27 AND a2 >= 28 AND a2 < 38')
(62, 4, 1, 'synth_4_clean_1', 'synth_4_clean_2', 'clean', 'UPDATE', '[]', '[["a3", 86], ["a2", 88]]', '[["a4", ">=", 7], ["a4", "<", 17], ["a2", ">=", 55], ["a2", "<", 65]]', 'UPDATE synth_4_clean_1 SET a3 = 86, a2 = 88 WHERE a4 >= 7 AND a4 < 17 AND a2 >= 55 AND a2 < 65')
(63, 4, 2, 'synth_4_clean_2', 'synth_4_clean_3', 'clean', 'UPDATE', '[]', '[["a3", 17], ["a2", 47]]', '[["a4", ">=", 8], ["a4", "<", 18], ["a2", ">=", 85], ["a2", "<", 95]]', 'UPDATE synth_4_clean_2 SET a3 = 17, a2 = 47 WHERE a4 >= 8 AND a4 < 18 AND a2 >= 85 AND a2 < 95')
(64, 4, 3, 'synth_4_clean_3', 'synth_4_clean_4', 'clean', 'UPDATE', '[]', '[["a3", 30], ["a2", 91]]', '[["a4", ">=", 52], ["a4", "<", 62], ["a2", ">=", 80], ["a2", "<", 90]]', 'UPDATE synth_4_clean_3 SET a3 = 30, a2 = 91 WHERE a4 >= 52 AND a4 < 62 AND a2 >= 80 AND a2 < 90')
(65, 4, 4, 'synth_4_clean_4', 'synth_4_clean_5', 'clean', 'UPDATE', '[]', '[["a3", 41], ["a2", 60]]', '[["a4", ">=", 39], ["a4", "<", 49], ["a2", ">=", 14], ["a2", "<", 24]]', 'UPDATE synth_4_clean_4 SET a3 = 41, a2 = 60 WHERE a4 >= 39 AND a4 < 49 AND a2 >= 14 AND a2 < 24')
(66, 4, 5, 'synth_4_clean_5', 'synth_4_clean_6', 'clean', 'INSERT', '[50, 82, 4, 4, 63, 28, 53]', '[]', '[]', 'INSERT INTO synth_4_clean_5 VALUES(50,82,4,4,63,28,53)')
(68, 4, 7, 'synth_4_clean_7', 'synth_4_clean_8', 'clean', 'UPDATE', '[]', '[["a3", 35], ["a2", 75]]', '[["a1", "=", 32], ["a0", "=", 56]]', 'UPDATE synth_4_clean_7 SET a3 = 35, a2 = 75 WHERE a1 = 32 AND a0 = 56')
(69, 4, 8, 'synth_4_clean_8', 'synth_4_clean_9', 'clean', 'UPDATE', '[]', '[["a3", 6], ["a2", 23]]', '[["a1", "=", 77], ["a0", "=", 62]]', 'UPDATE synth_4_clean_8 SET a3 = 6, a2 = 23 WHERE a1 = 77 AND a0 = 62')
(70, 4, 9, 'synth_4_clean_9', 'synth_4_clean_10', 'clean', 'INSERT', '[51, 33, 17, 46, 4, 70, 90]', '[]', '[]', 'INSERT INTO synth_4_clean_9 VALUES(51,33,17,46,4,70,90)')
(71, 4, 0, 'synth_4_dirty_0', 'synth_4_dirty_1', 'dirty', 'UPDATE', '[]', '[["a3", 81], ["a2", 80]]', '[["a4", ">=", 17], ["a4", "<", 27], ["a2", ">=", 28], ["a2", "<", 38]]', 'UPDATE synth_4_dirty_0 SET a3 = 81, a2 = 80 WHERE a4 >= 17 AND a4 < 27 AND a2 >= 28 AND a2 < 38')
(72, 4, 1, 'synth_4_dirty_1', 'synth_4_dirty_2', 'dirty', 'UPDATE', '[]', '[["a3", 86], ["a2", 88]]', '[["a4", ">=", 7], ["a4", "<", 17], ["a2", ">=", 55], ["a2", "<", 65]]', 'UPDATE synth_4_dirty_1 SET a3 = 86, a2 = 88 WHERE a4 >= 7 AND a4 < 17 AND a2 >= 55 AND a2 < 65')
(73, 4, 2, 'synth_4_dirty_2', 'synth_4_dirty_3', 'dirty', 'UPDATE', '[]', '[["a3", 17], ["a2", 47]]', '[["a4", ">=", 8], ["a4", "<", 18], ["a2", ">=", 85], ["a2", "<", 95]]', 'UPDATE synth_4_dirty_2 SET a3 = 17, a2 = 47 WHERE a4 >= 8 AND a4 < 18 AND a2 >= 85 AND a2 < 95')
(74, 4, 3, 'synth_4_dirty_3', 'synth_4_dirty_4', 'dirty', 'UPDATE', '[]', '[["a3", 30], ["a2", 91]]', '[["a4", ">=", 52], ["a4", "<", 62], ["a2", ">=", 80], ["a2", "<", 90]]', 'UPDATE synth_4_dirty_3 SET a3 = 30, a2 = 91 WHERE a4 >= 52 AND a4 < 62 AND a2 >= 80 AND a2 < 90')
(75, 4, 4, 'synth_4_dirty_4', 'synth_4_dirty_5', 'dirty', 'UPDATE', '[]', '[["a3", 41], ["a2", 60]]', '[["a4", ">=", 39], ["a4", "<", 49], ["a2", ">=", 14], ["a2", "<", 24]]', 'UPDATE synth_4_dirty_4 SET a3 = 41, a2 = 60 WHERE a4 >= 39 AND a4 < 49 AND a2 >= 14 AND a2 < 24')
(76, 4, 5, 'synth_4_dirty_5', 'synth_4_dirty_6', 'dirty', 'INSERT', '[50, 82, 4, 4, 63, 28, 53]', '[]', '[]', 'INSERT INTO synth_4_dirty_5 VALUES(50,82,4,4,63,28,53)')
(77, 4, 6, 'synth_4_dirty_6', 'synth_4_dirty_7', 'dirty', 'UPDATE', '[]', '[["a3", 100], ["a2", 19]]', '[["a1", "=", 41], ["a0", "=", 20]]', 'UPDATE synth_4_dirty_6 SET a3 = 100, a2 = 19 WHERE a1 = 41 AND a0 = 20')
(78, 4, 7, 'synth_4_dirty_7', 'synth_4_dirty_8', 'dirty', 'UPDATE', '[]', '[["a3", 35], ["a2", 75]]', '[["a1", "=", 32], ["a0", "=", 56]]', 'UPDATE synth_4_dirty_7 SET a3 = 35, a2 = 75 WHERE a1 = 32 AND a0 = 56')
(79, 4, 8, 'synth_4_dirty_8', 'synth_4_dirty_9', 'dirty', 'UPDATE', '[]', '[["a3", 82], ["a2", 23]]', '[["a1", "=", 77], ["a0", "=", 19]]', 'UPDATE synth_4_dirty_8 SET a3 = 82, a2 = 23 WHERE a1 = 77 AND a0 = 19')
(80, 4, 9, 'synth_4_dirty_9', 'synth_4_dirty_10', 'dirty', 'INSERT', '[51, 33, 17, 46, 4, 70, 90]', '[]', '[]', 'INSERT INTO synth_4_dirty_9 VALUES(51,33,17,46,4,70,90)')

In [42]:
curr = myConnection.cursor()
curr.execute('SELECT * FROM "qfix"')
rows = curr.fetchall()

UndefinedTable: relation "qfix" does not exist
LINE 1: SELECT * FROM "qfix"
                      ^

In [ ]:
curr = myConnection.cursor()
curr.execute("SELECT * FROM qlogs")
rows = cur.fetchall()